name: Makefile CI

on:
  push:
    branches: [ "udc" ]
  pull_request:
    branches: [ "udc" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      run: | 
       echo "Free space:"

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
